### PR TITLE
Add rubocop code analyzer

### PR DESCRIPTION
**Pull request by bkerley**
This is a pretty epic PR, but it shouldn't have any functional code changes, just style fixes and an addition to the build process.

### CODE REVIEW

**Comment by christophermancini** [comment]
Tests pass, rubocop has done well.

:+1: 2a030d2

**Comment by bkerley** [comment]
:+1: 2a030d2

**Comment by bkerley** [comment]
:+1: 61b2932

**Comment by bkerley** [comment]
@borshop merge

**Pull request merged**
