### PR TITLE
use bundler for dependency management

### PR DESCRIPTION
**Pull request by grosser**
@lukebakken

### CODE REVIEW

**Comment by lukebakken** [comment]
Can you explain the benefit(s) of this change? It's not immediately apparent to me why these changes should be made.

**Comment by grosser** [comment]
- loading rubygems is deprecated since 1.9
 - not using bundler means we get random gem versions (that might not even match Gemfile) AND it might even use undocumented gems that happened to be installed on the local system

**Comment by lukebakken** [comment]
Thanks for explaining and making these changes. I've merged your commit into #297

**Comment by grosser** [comment]
thx!

if you have a few minutes to spare, I got more PRs open ;)

**Comment by lukebakken** [comment]
Yep, I'll get to them as time allows.

**Pull request closed without merging**
