### PR TITLE
Ignore tags file if present

### PR DESCRIPTION
**Pull request by lukebakken**
I'm a `ctags` fan, what can I say.

### CODE REVIEW

**Comment by bkerley** [comment]
This should probably be in your local `.gitignore` setup, instead of the one shared by the project; however, it looks like it fits the precedent so vºv

**Comment by bkerley** [comment]
+1 4723afd

**Comment by lukebakken** [comment]
I always forget about a global `.gitignore`. I'll set that up too.

**Comment by bkerley** [comment]
+1 910befb

**Comment by bkerley** [comment]
@borshop merge

**Pull request merged**
