### PR TITLE
Riak Ruby Client 2.6.0

### PR DESCRIPTION
**Pull request by lukebakken**
Includes #291

### CODE REVIEW

**Comment by grosser** [comment]
👍

**Comment by grosser** [comment]
I'll make a followup PR to add coverage to all files next ... not sure when you are planing to merge 2.6

**Comment by lukebakken** [comment]
Today or tomorrow. No hurry on that follow-up PR.

**Comment by grosser** [comment]
1.9 builds are failing because then `unless defined?(SingleCov)` got lost ... do you want to bring this back or stop running tests on 1.9 ?

**Comment by lukebakken** [comment]
Yeah, let's put that back. Some of our supported operating systems ship with 1.9.3 so ....

**Comment by grosser** [comment]
I was wondering why the multi stuff got moved into integration even though they do not require a running riak instance ...

**Comment by lukebakken** [comment]
@grosser I saw a new client being instantiated and figured that it connected to Riak. I forgot that the Ruby client works differently than the other client libraries I work on as well.

Any insight into the jruby errors?

https://travis-ci.org/basho/riak-ruby-client/jobs/183472697

I can return to this PR once other, higher-priority work is done.

**Comment by grosser** [comment]
https://github.com/basho/riak-ruby-client/pull/300

**Pull request merged**
