### PR TITLE
simplify fetch list validation logic and move all validations into in…

### PR DESCRIPTION
**Pull request by grosser**
…itialize

@lukebakken

### CODE REVIEW

**Comment by grosser** [comment]
rebased and green now :)

**Comment by lukebakken** [comment]
@grosser would you mind rebasing this on `features/lrb/riak-client-2.6.0` and changing the base of this PR? Thanks.

**Comment by grosser** [comment]
rebased ... can you pick the latest commit ? ... otherwise I have to open a new PR to change the base

**Comment by lukebakken** [comment]
I'll get it, thanks.

**Comment by lukebakken** [comment]
Merged, but getting these two errors on `make unit-test`:

```

**Comment by grosser** [comment]
should not merge a red build :D

**Comment by grosser** [comment]
can delete the first test ... and change the other to nil

**Comment by lukebakken** [comment]
I'm too impatient to wait on travis today.

**Comment by lukebakken** [comment]
@grosser thanks, fixed in 47f15870574b8e535482476491967819065aa5d0

**Pull request merged**
