### PR TITLE
Multi-exist on buckets

### PR DESCRIPTION
**Pull request by lukebakken**
Includes #302

### CODE REVIEW

**Comment by grosser** [comment]
how about an release .. this is 6 months old now :D

**Comment by russelldb** [comment]
https://www.theregister.co.uk/2017/07/31/end_of_the_road_for_basho_as_court_puts_biz_into_receivership/

**Comment by grosser** [comment]
nooooOOOOO

**Comment by lukebakken** [comment]
@grosser - yep, @russelldb beat me to it

**Pull request merged**
