### PR TITLE
GETting an object from a bucket-typed bucket loses the bucket-type [JIRA: CLIENTS-308]

### PR DESCRIPTION
**Pull request by bkerley**
{{[51] pry(main)> b
=> #<Riak::BucketTyped::Bucket bucket_type=#<Riak::BucketType name=write_once> name=bryce>
[52] pry(main)> some_value = b.get_or_new 'bug'
=> #<Riak::RObject {bryce,bug} [#<Riak::RContent [application/json]:nil>]>
[53] pry(main)> some_value.bucket
=> #<Riak::BucketTyped::Bucket bucket_type=#<Riak::BucketType name=write_once> name=bryce>
[54] pry(main)> some_value.data = "CLIENTS-308 (#215) (#215) (#215) (#215) (#215)"
=> "CLIENTS-308 (#215) (#215) (#215) (#215) (#215)"
[55] pry(main)> some_value.store
=> #<Riak::RObject {bryce,bug} [#<Riak::RContent [application/json]:"CLIENTS-308 (#215) (#215) (#215) (#215) (#215)">]>
[56] pry(main)> b.get 'bug'
=> #<Riak::RObject {bryce,bug} [#<Riak::RContent [application/json]:"CLIENTS-308 (#215) (#215) (#215) (#215) (#215)">]>
[57] pry(main)> bug = b.get 'bug'
=> #<Riak::RObject {bryce,bug} [#<Riak::RContent [application/json]:"CLIENTS-308 (#215) (#215) (#215) (#215) (#215)">]>
[58] pry(main)> bug.bucket
=> #<Riak::Bucket name=bryce>
[59] pry(main)> bug.reload
Riak::ProtobuffsFailedRequest: Expected success from Riak but received not_found. The requested object was not found.
from /Users/bkerley/Documents/riak-ruby-client/lib/riak/client/beefcake_protobuffs_backend.rb:115:in `reload_object'}}

**[Created in JIRA by Bryce Kerley]**

### CODE REVIEW

**Comment by Basho-JIRA** [comment]
[~Bryce], should this be pulled into the current sprint? 

***[posted via JIRA by Derek Somogyi]***

**Comment by Basho-JIRA** [comment]
Probably; mostly knocked it out Monday, but it still needs review. 

***[posted via JIRA by Bryce Kerley]***

**Comment by christophermancini** [comment]
Discussed the PR with @bkerley, ran the tests and reviewed the code. All looks good.

**Comment by christophermancini** [comment]
:+1: 13af94a

**Comment by bkerley** [comment]
@borshop merge

**Pull request merged**
