### PR TITLE
Ruby Client:  Support gzip content encoding #246  [JIRA: CLIENTS-782]

### PR DESCRIPTION
**Pull request by boosty**
This PR allows setting `content_encoding` to `gzip` to automatically compress/decompress the object's data on store/load.

Based on a commit by @skaes: https://github.com/xing/riak-ruby-client/commit/1bdbbae066104ec4e423e33b5ddbc4d61d054a9e

### CODE REVIEW

**Comment by bkerley** [comment]
Hmm, not a huge fan of pulling ActiveSupport in for this feature. It could be conditionally added if ActiveSupport is present, similar to https://github.com/basho/riak-ruby-client/pull/189 . I'll see if I have time to work on that this week.

**Comment by boosty** [comment]
You are right. I was under the wrong impression that `ActiveSupport` would already be an implicit dependency. 

As an alternative to making the feature optional, maybe it's ok to just copy `ActiveSupport::Gzip`. Normally I would not recommend that of course, but in this case it's very little and simple code:
https://github.com/rails/rails/blob/master/activesupport/lib/active_support/gzip.rb

If you think that's ok I could update the PR accordingly.

**Comment by boosty** [comment]
@bkerley: I removed the `activesupport` gem dependency by copying the relevant `Gzip` code and tests. Please have another look.

**Comment by bkerley** [comment]
Looping in @lukebakken since I no longer work on this project :)

**Comment by lukebakken** [comment]
Thank you, included in #273. I added a note about the copied code in `README.md`

**Pull request closed without merging**
